#ifndef DM510_IOCTL_COMMANDS
#define DM510_IOCTL_COMMANDS

#define GET_BUFFER_SIZE 0
#define SET_BUFFER_SIZE 1
#define GET_MAX_NR_PROC 2
#define SET_MAX_NR_PROC 3
#define GET_BUFFER_FREE_SPACE 4
#define GET_BUFFER_USED_SPACE 5

#define DEVICE_COUNT 2
#define BUFFER_COUNT 2

#endif /* end of include guard: DM510_IOCTL_COMMANDS */
